version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: leadpages_python_coding_challenge
    environment:
      - APP_ENV=prod
      - EXTERNAL_API_SERVER_URL=http://localhost:3123/api/v1
    volumes:
      - ./backend/app:/code/app
    ports:
      - 8000:8000