FROM python:3.13.0-alpine3.20

WORKDIR /code

# For development purposes
COPY restart /usr/local/bin/restart

# Install dependencies
COPY requirements.txt /code/requirements.txt
RUN pip3 install -r requirements.txt

EXPOSE 6132

CMD ["tail", "-f", "/dev/null"]