FROM python:3.12-alpine

WORKDIR /code

# Install dependencies
COPY requirements.txt /code/requirements.txt
RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]